const express = require("express");
const { createUser, loginUserController, getaUser, getallUser, deleteaUser, updateaUser } = require("../controller/userController");
const authMiddleware = require("../middlewares/authMiddleware");
const router = express.Router();
router.post("/register", createUser);
router.post("/login", loginUserController);
router.get("/all-users", getallUser);
router.get("/:id", authMiddleware, getaUser);
router.delete("/:id", deleteaUser);
router.put("/:id", updateaUser);
module.exports = router;